use dev;

CREATE TABLE `dev`.`T_BOARD_BOARD` (
`NO` INT PRIMARY KEY AUTO_INCREMENT, 
`TITLE` VARCHAR(100) NOT NULL, 
`WRITER` VARCHAR(100) NOT NULL, 
`CONTENT` VARCHAR(100), 
`CREATED_DATE` DATETIME NOT NULL, 
`UPDATED_DATE` DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `dev`.`T_COMMENT_BOARD` (
`NO` INT PRIMARY KEY AUTO_INCREMENT,
`WRITER` VARCHAR(100) NOT NULL,
`CONTENT` VARCHAR(100),
`CREATED_DATE` DATETIME NOT NULL,
`UPDATED_DATE` DATETIME DEFAULT CURRENT_TIMESTAMP,
`BNO` INT,
FOREIGN KEY (`BNO`) REFERENCES T_BOARD_BOARD(`NO`)
);

commit;